services:
  backend:
    build: .
    container_name: backend_container
    ports:
      - 8080:8080
    environment:
      db-url: jdbc:postgresql://database:5432/my_db
      db-username: postgres
      db-password: 123456
    depends_on:
      - database

  database:
    container_name: db_container
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    restart: always
